version: "3.9"

services:
  fastapi:
    build:
      context: .
      dockerfile: Dockerfile
    command: uvicorn main:app --reload --host=0.0.0.0 --port=8000
    ports:
      - 8000:8000
    volumes:
      - ./app:/code/app
    container_name: 'dailyq-prod'