version: "3.9"

services:
  fastapi:
    build:
      context: .
      dockerfile: Dockerfile
    command: uvicorn main:app --reload --host=0.0.0.0 
    ports:
      - 80:80
    volumes:
      - ./app:/code/app
    container_name: 'test'